### PR TITLE
Common cathode as option

### PR DESCRIPTION
**Pull request by asergunov**
Adds a common cathode flag

### CODE REVIEW

**Review by I-hate-2FA — APPROVED** [review]
same as upstream

**Comment by asergunov** [comment]
@I-hate-2FA Hi. I've updated it to have code enum. I don't have device around to test. Could you please test if it works?

**Comment by I-hate-2FA** [comment]
didnt work, or i didnt know how to use it correctly

```
Compiling .pioenvs/esphome-trash-can/src/main.cpp.o
/config/esphome-trash-can.yaml: In function 'void setup()':
/config/esphome-trash-can.yaml:500:62: error: 'CommonAnode' is not a member of 'esphome::lcd_digits::LcdDigitsComponent'
*** [.pioenvs/esphome-trash-can/src/main.cpp.o] Error 1
========================= [FAILED] Took 65.51 seconds =========================
```

```
display:
- platform: 7segment_gpio
  id: sevenseg
  segment_pins: [4, 16, 17, 5, 18, 23, 19]
  display_type: COMMONANODE
  update_interval: 100ms
  lambda: |-
    if(id(keepon).state){
      if((millis()%2000) < 500){
        it.printf(0,"O");
      }else if((millis()%2000) < 1000){
        it.printf(0,"P");
      }else if((millis()%2000) < 1500){
        it.printf(0,"E");
      }else{
        it.printf(0,"n");
      } 
    }else if(id(ledr).state){
      it.printf(0,"%d",id(timer));
    }else{  
      it.printf(0,"H");
    }
```

**Comment by asergunov** [comment]
@I-hate-2FA I know what is it. Try now.

**Comment by asergunov** [comment]
Found another bug. Give me a sec

**Comment by asergunov** [comment]
@I-hate-2FA now should be fine

**Comment by I-hate-2FA** [comment]
its even worse now

```
Compiling .pioenvs/esphome-trash-can/src/main.cpp.o
/config/esphome-trash-can.yaml: In function 'void setup()':
/config/esphome-trash-can.yaml:500:62: error: 'CommonAnode' is not a member of 'esphome::lcd_digits::LcdDigitsComponent'
/config/esphome-trash-can.yaml:97:28: error: 'lcd_digits' is not a type
             - lambda: "return !(id(motor_moving).state);"
                            ^~~~~~~~~~
/config/esphome-trash-can.yaml: In lambda function:
/config/esphome-trash-can.yaml:159:14: error: request for member 'printf' in 'it', which is of non-class type 'int'
         it.printf(0,"O");
              ^~~~~~
/config/esphome-trash-can.yaml:161:14: error: request for member 'printf' in 'it', which is of non-class type 'int'
         it.printf(0,"P");
              ^~~~~~
/config/esphome-trash-can.yaml:163:14: error: request for member 'printf' in 'it', which is of non-class type 'int'
         it.printf(0,"E");
              ^~~~~~
/config/esphome-trash-can.yaml:165:14: error: request for member 'printf' in 'it', which is of non-class type 'int'
         it.printf(0,"n");
              ^~~~~~
/config/esphome-trash-can.yaml:168:12: error: request for member 'printf' in 'it', which is of non-class type 'int'
       it.printf(0,"%d",id(timer));
            ^~~~~~
/config/esphome-trash-can.yaml:170:12: error: request for member 'printf' in 'it', which is of non-class type 'int'
       it.printf(0,"H");
            ^~~~~~
/config/esphome-trash-can.yaml: In function 'void setup()':
/config/esphome-trash-can.yaml:172:4: error: no matching function for call to 'esphome::lcd_digits::LcdDigitsComponent::set_writer(setup()::<lambda(int&)>)'
 
    ^
In file included from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/components/7segment_gpio/7segment_gpio.h:86:8: note: candidate: 'void esphome::lcd_digits::LcdDigitsComponent::set_writer(esphome::lcd_digits::lcd_digits_writer_t&&)'
   void set_writer(lcd_digits_writer_t &&writer);
        ^~~~~~~~~~
src/esphome/components/7segment_gpio/7segment_gpio.h:86:8: note:   no known conversion for argument 1 from 'setup()::<lambda(int&)>' to 'esphome::lcd_digits::lcd_digits_writer_t&&' {aka 'std::function<void(esphome::lcd_digits::LcdDigitsComponent&)>&&'}
*** [.pioenvs/esphome-trash-can/src/main.cpp.o] Error 1
========================= [FAILED] Took 65.07 seconds =========================
```

**Comment by asergunov** [comment]
@I-hate-2FA my bad. Please try again

**Comment by I-hate-2FA** [comment]
still doesnt work

```
Compiling .pioenvs/esphome-trash-can/src/main.cpp.o
/config/esphome-trash-can.yaml: In function 'void setup()':
/config/esphome-trash-can.yaml:97:28: error: 'lcd_digits' is not a type
             - lambda: "return !(id(motor_moving).state);"
                            ^~~~~~~~~~
/config/esphome-trash-can.yaml: In lambda function:
/config/esphome-trash-can.yaml:159:14: error: request for member 'printf' in 'it', which is of non-class type 'int'
         it.printf(0,"O");
              ^~~~~~
/config/esphome-trash-can.yaml:161:14: error: request for member 'printf' in 'it', which is of non-class type 'int'
         it.printf(0,"P");
              ^~~~~~
/config/esphome-trash-can.yaml:163:14: error: request for member 'printf' in 'it', which is of non-class type 'int'
         it.printf(0,"E");
              ^~~~~~
/config/esphome-trash-can.yaml:165:14: error: request for member 'printf' in 'it', which is of non-class type 'int'
         it.printf(0,"n");
              ^~~~~~
/config/esphome-trash-can.yaml:168:12: error: request for member 'printf' in 'it', which is of non-class type 'int'
       it.printf(0,"%d",id(timer));
            ^~~~~~
/config/esphome-trash-can.yaml:170:12: error: request for member 'printf' in 'it', which is of non-class type 'int'
       it.printf(0,"H");
            ^~~~~~
/config/esphome-trash-can.yaml: In function 'void setup()':
/config/esphome-trash-can.yaml:172:4: error: no matching function for call to 'esphome::lcd_digits::LcdDigitsComponent::set_writer(setup()::<lambda(int&)>)'
 
    ^
In file included from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/components/7segment_gpio/7segment_gpio.h:86:8: note: candidate: 'void esphome::lcd_digits::LcdDigitsComponent::set_writer(esphome::lcd_digits::lcd_digits_writer_t&&)'
   void set_writer(lcd_digits_writer_t &&writer);
        ^~~~~~~~~~
src/esphome/components/7segment_gpio/7segment_gpio.h:86:8: note:   no known conversion for argument 1 from 'setup()::<lambda(int&)>' to 'esphome::lcd_digits::lcd_digits_writer_t&&' {aka 'std::function<void(esphome::lcd_digits::LcdDigitsComponent&)>&&'}
*** [.pioenvs/esphome-trash-can/src/main.cpp.o] Error 1
========================= [FAILED] Took 64.33 seconds =========================
```

**Comment by asergunov** [comment]
@I-hate-2FA found it. Please try again

**Comment by I-hate-2FA** [comment]
it still doesnt work
i had to repair my pc a bit now im back

```
Compiling .pioenvs/esphome-trash-can/src/esphome/components/7segment_gpio/7segment_gpio.cpp.o
Compiling .pioenvs/esphome-trash-can/src/main.cpp.o
src/esphome/components/7segment_gpio/7segment_gpio.cpp: In lambda function:
src/esphome/components/7segment_gpio/7segment_gpio.cpp:379:33: error: 'display_type' was not declared in this scope
     const auto digit_on_level = display_type == CommonAnode;
                                 ^~~~~~~~~~~~
src/esphome/components/7segment_gpio/7segment_gpio.cpp:379:33: note: suggested alternative: 'DisplayType'
     const auto digit_on_level = display_type == CommonAnode;
                                 ^~~~~~~~~~~~
                                 DisplayType
src/esphome/components/7segment_gpio/7segment_gpio.cpp: In lambda function:
src/esphome/components/7segment_gpio/7segment_gpio.cpp:384:35: error: 'display_type' was not declared in this scope
     const auto segment_on_level = display_type != CommonAnode;
                                   ^~~~~~~~~~~~
src/esphome/components/7segment_gpio/7segment_gpio.cpp:384:35: note: suggested alternative: 'DisplayType'
     const auto segment_on_level = display_type != CommonAnode;
                                   ^~~~~~~~~~~~
                                   DisplayType
src/esphome/components/7segment_gpio/7segment_gpio.cpp: In member function 'void esphome::lcd_digits::LcdDigitsComponent::set_progress(float)':
src/esphome/components/7segment_gpio/7segment_gpio.cpp:391:44: error: invalid use of void expression
       pin->digital_write(digit_level(false));
                                            ^
src/esphome/components/7segment_gpio/7segment_gpio.cpp:394:44: error: invalid use of void expression
     pin->digital_write(segment_level(false));
                                            ^
src/esphome/components/7segment_gpio/7segment_gpio.cpp:395:83: error: invalid use of void expression
   interrupt_data_.segment_pins[current_segment]->digital_write(segment_level(true));
                                                                                   ^
src/esphome/components/7segment_gpio/7segment_gpio.cpp:397:41: error: invalid use of void expression
     pin->digital_write(digit_level(true));
                                         ^
*** [.pioenvs/esphome-trash-can/src/esphome/components/7segment_gpio/7segment_gpio.cpp.o] Error 1
========================= [FAILED] Took 89.51 seconds =========================
```

**Comment by asergunov** [comment]
@I-hate-2FA Sure. Have your time. Fixed this. Let me know if it works.

**Comment by asergunov** [comment]
Just realized I don't have device but have config. So I can compile on my side. It's compiling fine now. @I-hate-2FA Please validate if display works.

**Comment by I-hate-2FA** [comment]
both common anode and common cathode works

**Comment by asergunov** [comment]
@I-hate-2FA Awesome. Thanks again. I'm merging

**Comment by I-hate-2FA** [comment]
i sugest to use `common_anode` or `commonAnode` insted of `COMMONANODE`

**Comment by I-hate-2FA** [comment]
but its up to you

**Review by I-hate-2FA — APPROVED** [review]
work as expected, see comment for improvement

**Comment by asergunov** [comment]
I've added underscore. It should work in upper or lower case as I understand.

**Comment by I-hate-2FA** [comment]
i go checked other esphome internal component enum and indeed they used all upper case with underscore

**Comment by asergunov** [comment]
Yup. Done the same. Also there is option in enum config parser to convert to upper or lower case. I think it will work the same way if you write lowercase with underscore in configuration.

**Comment by I-hate-2FA** [comment]
the readme need to be updated too

**Comment by asergunov** [comment]
Updated in main. Please let me know what could be improved there.

**Comment by asergunov** [comment]
I'm going to delete this branch. Please switch to main in your project config.

**Comment by asergunov** [comment]
@I-hate-2FA Thanks again for your help!

**Comment by I-hate-2FA** [comment]
had to deal with the pc again
hopefully stable now

maybe you can add it in the example code below, or if this option is optional (it shouldnt be, right?) you can choose not to

**Comment by asergunov** [comment]
I've added
```yaml
   # display_type: common_cathode # Uncomment this line for common cathode display
```

**Pull request merged**
